### ISSUE TITLE
I get Error during Scaffolding

### ISSUE THREAD

**Issue by Zedonboy** [tobias-walle/rush#3]
```
`Create the project folder "shopvie".
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '../configuration'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.createInitialDefaultConfiguration (/home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/utils/yo-rc-utils.js:9:25)
    at module.exports.writing (/home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/generators/app/index.js:165:27)
    at Object.<anonymous> (/home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/node_modules/yeoman-generator/lib/index.js:417:23)
    at /home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/node_modules/run-async/index.js:24:19
Emitted 'error' event at:
    at Immediate.<anonymous> (/home/declan/.nvm/versions/node/v10.9.0/lib/node_modules/generator-rush/node_modules/yeoman-generator/lib/index.js:424:16)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
`
```

**Comment by TobiasWalle** [comment]
Thank you for creating this issue. Unfortunately I do not maintain this project anymore.
If you want to scaffold a project for React with Typescript, I recommend https://github.com/facebook/create-react-app
